### ISSUE TITLE
Automatic updating repo

### ISSUE THREAD

**Issue by Quantum-Codes** [AwesomePotato23/ScraBrowse#1]
If you connect your github to replit, and commit from replit, then github also will automatically update it!
If any problems, you may ask :)

**Comment by Quantum-Codes** [comment]
Steps: 
1. go to replit and connect your github
2. Go to your scrabrowse on replit and select the button below the files button (it will be written create git)
3. Click on **create** then connect it to your github repo
4. Done! Every time you change some code on replit, click on commit button and it's automatically reflected here!

**Comment by Quantum-Codes** [comment]
@AwesomePotato23

**Comment by AwesomePotato23** [comment]
Thanks!
